name: CI/CD

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: kuhnroyal/flutter-fvm-config-action@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
